name: parallax_image
description: A Flutter widget that paints an image and moves it at a slower speed than the main scrolling content.
version: 0.2.0+1
homepage: https://github.com/pulyaevskiy/parallax-image
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  flutter:
    sdk: flutter

# dev_dependencies:
#   test: ^0.12.0
